bind:
  http: 8080
  grpc: 6500

database:
  host: localhost
  port: 3306
  username: root
  password: yash
  database: user_management_db

instrument:
  enabled: false
  collector_address: 172.26.4.70:4318
  